require("plugin_config.colors")

require("plugin_config.fugitive")
require("plugin_config.harpoon")
require("plugin_config.null-ls")
require("plugin_config.telescope")
require("plugin_config.tint")
require("plugin_config.toggleterm")
require("plugin_config.undotree")
require("plugin_config.lualine")
require("plugin_config.git-signs")
require("plugin_config.whichkey")
require("plugin_config.alpha-config")
require("plugin_config.auto-pairs-config")
require("plugin_config.indent-line-config")
