require("plugin_config.colors")
require("plugin_config.language")

require("plugin_config.fugitive")
require("plugin_config.harpoon")
require("plugin_config.null-ls")
require("plugin_config.telescope")
require("plugin_config.tint")
require("plugin_config.toggleterm")
require("plugin_config.undotree")
