require("plugin-config.appearance.colors")
require("plugin-config.appearance.illuminate")
require("plugin-config.appearance.treesitter")
require("plugin-config.appearance.lualine")
require("plugin-config.appearance.tint")
require("plugin-config.appearance.changes-in-files")
