require("plugin_config.appearance.colors")
require("plugin_config.appearance.illuminate")
require("plugin_config.appearance.treesitter")
require("plugin_config.appearance.lualine")
require("plugin_config.appearance.tint")
require("plugin_config.appearance.changes-in-files")
require("plugin_config.appearance.alpha-config")
